load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

RULES_JVM_EXTERNAL_TAG = "4.0"
RULES_JVM_EXTERNAL_SHA = "31701ad93dbfe544d597dbe62c9a1fdd76d81d8a9150c2bf1ecf928ecdf97169"

http_archive(
    name = "rules_jvm_external",
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    sha256 = RULES_JVM_EXTERNAL_SHA,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)

load("@rules_jvm_external//:defs.bzl", "maven_install")
maven_install(
    artifacts = [
        "org.apache.commons:commons-lang3:3.11",
        "org.springframework:spring-web:5.3.6",
        "org.springframework:spring-beans:5.3.6",
        "org.projectlombok:lombok:1.18.20",
        "org.springframework.data:spring-data-commons:2.4.8",
        "org.springframework.data:spring-data-mongodb:3.1.8",
        "org.springframework:spring-context:5.3.6",
        "org.springframework.boot:spring-boot:2.4.5",
        "org.springframework.boot:spring-boot-starter-web:2.4.5",
        "org.springframework.boot:spring-boot-autoconfigure:2.4.5",
        "io.springfox:springfox-swagger2:2.9.2",
        "org.slf4j:slf4j-nop:1.7.30"
         ],
    repositories = [
        "https://repo1.maven.org/maven2",
    ] )